### ISSUE TITLE
docker-elk does not stand up correctly (logstash exits with code 1)

### ISSUE THREAD

**Issue by beezel** [thomaspatzke/logstash-linux#1]
Trying to use this as a stand alone ELK stack along side our Postfix server and I'm having some troubles getting the docker-compose to stand up. 

Trying either with or without x-pack results in the same error from Logstash, then it exits:

Sending Logstash's logs to /usr/share/logstash/logs which is now configured via log4j2.properties
[2018-05-09T19:33:51,708][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.url" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:37:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:70:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:89:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:89:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:138:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:264:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:219:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:67:in `<main>'"]}
[2018-05-09T19:33:51,794][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit

It appears to be trying to use xpack, but it isn't installed. This is the case for both docker-compose-oss.yml and docker-compose-with-xpack.yml files.

Any ideas? I can get the standard docker-elk stack to stand up just fine, but would love to have an easy-to-deploy tool like yours setup.

**Comment by thomaspatzke** [comment]
Hi! Thanks for submitting this issue. Unfortunately I can't reproduce it with *docker-compose-elk-with-x-pack.yml*, but with *docker-compose-elk-oss.yml*. Actually, the Logstash configuration option *xpack.monitoring.elasticsearch.url* is not supported when X-Pack is not present, but contained in the configuration shared by both Docker environments.

I fixed this by separating the Logstash config into a version for each environemnt. Along with the fix I've updated all components to the current version 6.2.4 in a further commit. Please try again with the current version.

**Comment by thomaspatzke** [comment]
I think the issue appeared in both flavours of the Docker environments because Docker used the previously built OSS Logstash container instead of the X-Pack container. Think that's an issue caused by the same container name in both environemnts.

**Comment by beezel** [comment]
Thanks for the quick response. I apologize for missing the obvious with cached images of same name.

However, after rm'ing everything, running docker system prune -a, re-cloning and rebuilding, I am still getting a failure.

This is different, and maybe seems to be related to spamd.grok? I can't tell much from the error, personally.

Are you having success standing this up? I've tried both oss and with-x-pack (after doing docker system prune -a again, of course). Both crap out the same way.

`[2018-05-11T22:03:15,721][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::FilterDelegator:0x517c52af @metric_events_out=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0, @metric_events_in=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0, @metric_events_time=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0, @id=\"7a9fc032624355354547db41329624d2ce7c0edb944207902a33d61b138af8d4\", @klass=LogStash::Filters::Grok, @metric_events=#<LogStash::Instrument::NamespacedMetric:0xee2f34e @metric=#<LogStash::Instrument::Metric:0x14bb9d33 @collector=#<LogStash::Instrument::Collector:0x51a76746 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x627dbef7 @store=#<Concurrent::Map:0x00000000000fc0 entries=3 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x59f1cd51>, @fast_lookup=#<Concurrent::Map:0x00000000000fc4 entries=219 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :filters, :\"7a9fc032624355354547db41329624d2ce7c0edb944207902a33d61b138af8d4\", :events]>, @filter=<LogStash::Filters::Grok patterns_dir=>[\"/usr/share/logstash/pipeline/patterns.d\"], match=>{\"message\"=>\"%{PAM}\"}, add_tag=>[\"_grok_pam_success\"], id=>\"7a9fc032624355354547db41329624d2ce7c0edb944207902a33d61b138af8d4\", enable_metric=>true, periodic_flush=>false, patterns_files_glob=>\"*\", break_on_match=>true, named_captures_only=>true, keep_empty_captures=>false, tag_on_failure=>[\"_grokparsefailure\"], timeout_millis=>30000, tag_on_timeout=>\"_groktimeout\">>", :error=>"Grok pattern file does not exist: /usr/share/logstash/pipeline/patterns.d/spamd.grok", :thread=>"#<Thread:0x4fbae6d4 run>"}
[2018-05-11T22:03:16,365][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<RuntimeError: Grok pattern file does not exist: /usr/share/logstash/pipeline/patterns.d/spamd.grok>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:401:in `block in add_patterns_from_files'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:399:in `add_patterns_from_files'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:279:in `block in register'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:275:in `block in register'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:270:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:731:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:363:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0x4fbae6d4 run>"}
[2018-05-11T22:03:16,456][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}
`
